/**
 * Promptfoo provider that loads the locally cached e2e bot transcript
 * as the "model under test's output". Each test's llm-rubric then
 * grades that transcript through a different stakeholder lens.
 *
 * The transcript is generated by:
 *   bin/e2e.sh stakeholder-sim-onboarding
 * which dumps it on the SSH host. The wrapper bin/promptfoo-transcript.sh
 * rsyncs it back to tests/qa-output/ before running promptfoo.
 *
 * No LLM call here — this is just a file loader. The grader LLM
 * (Claude) is invoked by the llm-rubric assertion downstream.
 *
 * Promptfoo expects this module's default export to be a CLASS that
 * it can `new`. The class needs an `id()` method and an async
 * `callApi(prompt, context)` method.
 */
import { readFileSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE       = dirname( fileURLToPath( import.meta.url ) );
const PROJECT    = join( HERE, '..', '..' );
const TRANSCRIPT = join( PROJECT, 'tests', 'qa-output', 'stakeholder-sim-onboarding.txt' );

class TranscriptLoader {
  id() {
    return 'transcript-loader';
  }

  async callApi() {
    try {
      const text  = readFileSync( TRANSCRIPT, 'utf8' );
      const stats = statSync( TRANSCRIPT );
      const ageS  = Math.floor( ( Date.now() - stats.mtimeMs ) / 1000 );
      const header = `_local transcript loaded · ${ stats.mtime.toISOString() } · age ${ ageS }s · ${ text.length } chars_\n\n`;
      return { output: header + text };
    } catch ( e ) {
      return {
        output: '',
        error:  `transcript not found at ${ TRANSCRIPT }: ${ e.message }. Run \`bin/promptfoo-transcript.sh refresh\` first.`,
      };
    }
  }
}

export default TranscriptLoader;
