<?php
/**
 * CPT-backed data access.
 *
 * @package Mantia
 */

defined( 'ABSPATH' ) || exit;

final class Mantia_Repository {

	public const META_PHONE              = '_mantia_phone';
	public const META_WHATSAPP_RECIPIENT = '_mantia_whatsapp_recipient';
	public const META_GROUP_IDS          = '_mantia_group_ids';
	public const META_ACTIVE_GROUP_ID    = '_mantia_active_group_id';
	public const META_INVITE_CODE        = '_mantia_invite_code';
	public const META_GROUP_SLUG         = '_mantia_group_slug';
	public const META_EXTERNAL_ID        = '_mantia_external_id';
	public const META_HOME_TEAM          = '_mantia_home_team';
	public const META_AWAY_TEAM          = '_mantia_away_team';
	public const META_KICKOFF_GMT        = '_mantia_kickoff_gmt';
	public const META_KICKOFF_TS         = '_mantia_kickoff_ts';
	public const META_PHASE              = '_mantia_phase';
	public const META_STATUS             = '_mantia_status';
	public const META_HOME_SCORE         = '_mantia_home_score';
	public const META_AWAY_SCORE         = '_mantia_away_score';
	public const META_RESOLVED           = '_mantia_resolved';
	public const META_USER_ID            = '_mantia_user_id';
	public const META_USER_PHONE         = '_mantia_user_phone';
	public const META_MATCH_ID           = '_mantia_match_id';
	public const META_GROUP_ID           = '_mantia_group_id';
	public const META_PRED_HOME_SCORE    = '_mantia_predicted_home_score';
	public const META_PRED_AWAY_SCORE    = '_mantia_predicted_away_score';
	public const META_POINTS             = '_mantia_points';
	public const META_SCORING_REASON     = '_mantia_scoring_reason';
	public const META_SCORED             = '_mantia_scored';
	// Marks a prediction that was generated by auto-fill (not manually
	// entered by the user). The "tus pronósticos siguen siendo random
	// hasta que los cambies" hint on /me/ shows only when every one of
	// the user's predictions still has this flag set.
	public const META_AUTO_FILLED        = '_mantia_auto_filled';

	// Sweepstake assignment (one team per user × group). The /sortear
	// command shuffles teams from the group's competition and persists
	// each member's draw here so workflows can push "your team plays today"
	// reminders. Suffix the meta key with group_id so a user in N pencas
	// can have N independent draws.
	public const META_SWEEPSTAKE_TEAM    = '_mantia_sweepstake_team_';

	public static function normalize_phone( string $phone ): string {
		if ( str_contains( $phone, '@' ) ) {
			$phone = preg_replace( '/^([^:@]+):\d+(@.*)$/', '$1$2', strtolower( $phone ) );
			$phone = substr( (string) $phone, 0, (int) strpos( (string) $phone, '@' ) );
		}

		return preg_replace( '/\D+/', '', $phone ) ?: '';
	}

	public static function normalize_invite_code( string $invite_code ): string {
		$invite_code = function_exists( 'remove_accents' ) ? remove_accents( $invite_code ) : $invite_code;
		$invite_code = strtoupper( (string) $invite_code );
		$invite_code = preg_replace( '/[^A-Z0-9_-]+/', '', $invite_code );

		return substr( (string) $invite_code, 0, 32 );
	}

	/**
	 * Find-or-create a Mantia user. Identity lives in a wp_user (managed by
	 * WA_Identity_Bridge); Mantia-specific per-user state (active group,
	 * whatsapp recipient, etc.) lives in user_meta on the same row.
	 *
	 * Returns 0 on bad phone OR if wp_user creation failed (rate limit,
	 * filter rejection). Callers must handle the 0 case — the WhatsApp
	 * flow returns a generic "no pude identificarte, reintentá" reply.
	 */
	public static function get_or_create_user( string $phone, string $name = '', string $recipient = '' ): int {
		$normalized = self::normalize_phone( $phone );
		if ( '' === $normalized ) {
			return 0;
		}

		$user = WA_Identity_Bridge::resolve_or_create( $normalized, $name );
		if ( ! ( $user instanceof WP_User ) ) {
			return 0;
		}

		if ( '' !== $recipient ) {
			update_user_meta( $user->ID, self::META_WHATSAPP_RECIPIENT, sanitize_text_field( $recipient ) );
		}
		// Mirror the canonical phone into our own meta key too — most callers
		// use META_PHONE for lookup and we want to keep both keys in sync so
		// neither becomes the "wrong" source of truth.
		update_user_meta( $user->ID, self::META_PHONE, $normalized );

		return (int) $user->ID;
	}

	/**
	 * Format an E.164 phone for human display when the user never told us
	 * a name. Insert spaces to break up the digits — "+598 99 139 203"
	 * is more scannable than "59899139203". Falls back to the raw value
	 * if the number is too short to format meaningfully.
	 */
	public static function format_phone_for_display( string $phone ): string {
		$digits = preg_replace( '/\D+/', '', $phone );
		if ( '' === $digits ) {
			return $phone;
		}
		$len = strlen( $digits );
		// Group the trailing digits as 3-3-3 (or 3-3-2) for readability.
		// Country-code prefix stays as-is on the left.
		if ( $len <= 8 ) {
			return '+' . $digits;
		}
		// Last 9 digits → " NN NNN NNN" or " NN NNN NN" pattern.
		$tail_len = min( 9, $len - 2 ); // keep at least the country code on the left
		$head     = substr( $digits, 0, $len - $tail_len );
		$tail     = substr( $digits, -$tail_len );
		$grouped  = trim( preg_replace( '/(\d{3})(?=\d)/', '$1 ', $tail ) );
		return '+' . $head . ' ' . $grouped;
	}

	/**
	 * Resolve a user's display name, falling back through:
	 *   1. wp_user.display_name (the canonical, WhatsApp profile.name source)
	 *   2. Formatted phone (so unnamed users still appear as +598 99 139 203)
	 *   3. Generic 'Jugador' label.
	 *
	 * Used everywhere we need to render a user's name in a UI surface.
	 * Centralised so the fallback ladder stays consistent.
	 */
	public static function user_display_name( int $user_id ): string {
		$user = get_user_by( 'id', $user_id );
		if ( $user instanceof WP_User ) {
			$name = (string) $user->display_name;
			if ( '' !== $name ) {
				return $name;
			}
		}
		$phone = (string) get_user_meta( $user_id, self::META_PHONE, true );
		if ( '' !== $phone ) {
			return self::format_phone_for_display( $phone );
		}
		return __( 'Jugador', 'mantia' );
	}

	/**
	 * Find a Mantia user by phone. Delegates to WA_Identity_Bridge so the
	 * canonical META_PHONE meta key it uses (wa_phone_e164) is the source
	 * of truth; we keep our own META_PHONE meta in sync as a Mantia-side
	 * mirror for the few queries that filter by it directly.
	 */
	public static function find_user_by_phone( string $phone ): ?WP_User {
		$normalized = self::normalize_phone( $phone );
		if ( '' === $normalized ) {
			return null;
		}
		return WA_Identity_Bridge::find_by_phone( $normalized );
	}

	public static function create_group( string $name, string $invite_code = '', string $slug = '', string $competition_id = '' ): int {
		$name        = sanitize_text_field( $name );
		$invite_code = '' !== $invite_code ? self::normalize_invite_code( $invite_code ) : self::generate_invite_code( $name );
		$existing    = self::find_group_by_invite_code( $invite_code );
		if ( $existing ) {
			return (int) $existing->ID;
		}

		$post_id = wp_insert_post(
			array(
				'post_type'   => Mantia_CPTs::GROUP,
				'post_status' => 'publish',
				'post_title'  => $name,
			),
			true
		);

		if ( is_wp_error( $post_id ) ) {
			return 0;
		}

		$competition = '' !== $competition_id && Mantia_Competitions::get( $competition_id )
			? $competition_id
			: Mantia_Competitions::default_id();

		update_post_meta( (int) $post_id, self::META_INVITE_CODE, $invite_code );
		update_post_meta( (int) $post_id, self::META_GROUP_SLUG, '' !== $slug ? sanitize_title( $slug ) : sanitize_title( $name ) );
		update_post_meta( (int) $post_id, Mantia_Competitions::META_KEY, $competition );

		return (int) $post_id;
	}

	public static function group_competition_id( int $group_id ): string {
		$id = (string) get_post_meta( $group_id, Mantia_Competitions::META_KEY, true );
		return '' !== $id ? $id : Mantia_Competitions::default_id();
	}

	public const META_GROUP_VIEW_TOKEN  = '_mantia_group_view_token';
	public const META_USER_VIEW_TOKEN   = '_mantia_user_view_token';
	// SEPARATE share token for /me/share/<t>/ — must not equal the view
	// token. Otherwise anyone holding the share link could strip the
	// /share/ segment and land on the private edit page. Same token =
	// privacy break + write-access leak.
	public const META_USER_SHARE_TOKEN  = '_mantia_user_share_token';

	public static function group_view_token( int $group_id ): string {
		$token = (string) get_post_meta( $group_id, self::META_GROUP_VIEW_TOKEN, true );
		if ( '' === $token ) {
			$token = bin2hex( random_bytes( 12 ) );
			update_post_meta( $group_id, self::META_GROUP_VIEW_TOKEN, $token );
		}
		return $token;
	}

	/**
	 * Find a group by its slug — the post_meta the URL helpers emit since
	 * Phase 3. Falls back to slug-sanitised post_title if no explicit slug
	 * meta is set (older groups created before slug capture was wired).
	 */
	public static function find_group_by_slug( string $slug ): ?WP_Post {
		$slug = sanitize_title( $slug );
		if ( '' === $slug ) {
			return null;
		}
		$posts = get_posts(
			array(
				'post_type'      => Mantia_CPTs::GROUP,
				'post_status'    => 'publish',
				'posts_per_page' => 1,
				'no_found_rows'  => true,
				'meta_key'       => self::META_GROUP_SLUG,
				'meta_value'     => $slug,
			)
		);
		if ( ! empty( $posts ) ) {
			return $posts[0];
		}
		// Fallback: scan by title-derived slug. Rare path; we only hit this
		// if a group was created before META_GROUP_SLUG was being stamped.
		$candidates = get_posts(
			array(
				'post_type'      => Mantia_CPTs::GROUP,
				'post_status'    => 'publish',
				'posts_per_page' => -1,
				'no_found_rows'  => true,
			)
		);
		foreach ( $candidates as $p ) {
			if ( sanitize_title( (string) $p->post_title ) === $slug ) {
				return $p;
			}
		}
		return null;
	}

	public static function find_group_by_view_token( string $token ): ?WP_Post {
		$token = preg_replace( '/[^a-f0-9]/i', '', $token );
		if ( strlen( $token ) < 16 ) {
			return null;
		}
		$posts = get_posts(
			array(
				'post_type'      => Mantia_CPTs::GROUP,
				'post_status'    => 'publish',
				'posts_per_page' => 1,
				'no_found_rows'  => true,
				'meta_key'       => self::META_GROUP_VIEW_TOKEN,
				'meta_value'     => $token,
			)
		);
		return $posts[0] ?? null;
	}

	/**
	 * Legacy view / share tokens, now backed by user_meta. Phase 6 will
	 * remove these — the magic-link bridge replaces them for /pronostico/me/.
	 * Kept temporarily so existing URL handlers don't break mid-migration.
	 */
	public static function user_view_token( int $user_id ): string {
		$token = (string) get_user_meta( $user_id, self::META_USER_VIEW_TOKEN, true );
		if ( '' === $token ) {
			$token = bin2hex( random_bytes( 12 ) );
			update_user_meta( $user_id, self::META_USER_VIEW_TOKEN, $token );
		}
		return $token;
	}

	public static function find_user_by_view_token( string $token ): ?WP_User {
		$token = preg_replace( '/[^a-f0-9]/i', '', $token );
		if ( strlen( $token ) < 16 ) {
			return null;
		}
		$users = get_users( array(
			'meta_key'   => self::META_USER_VIEW_TOKEN,
			'meta_value' => $token,
			'number'     => 1,
			'fields'     => 'all',
		) );
		return $users[0] ?? null;
	}

	public static function user_share_token( int $user_id ): string {
		$token = (string) get_user_meta( $user_id, self::META_USER_SHARE_TOKEN, true );
		if ( '' === $token ) {
			do {
				$token = bin2hex( random_bytes( 12 ) );
			} while ( $token === (string) get_user_meta( $user_id, self::META_USER_VIEW_TOKEN, true ) );
			update_user_meta( $user_id, self::META_USER_SHARE_TOKEN, $token );
		}
		return $token;
	}

	public static function find_user_by_share_token( string $token ): ?WP_User {
		$token = preg_replace( '/[^a-f0-9]/i', '', $token );
		if ( strlen( $token ) < 16 ) {
			return null;
		}
		$users = get_users( array(
			'meta_key'   => self::META_USER_SHARE_TOKEN,
			'meta_value' => $token,
			'number'     => 1,
			'fields'     => 'all',
		) );
		return $users[0] ?? null;
	}

	/**
	 * Prefix used for QA / fixture-seeded groups. Surfaces (public competition
	 * leaderboard, etc.) filter these out so they never reach real visitors.
	 * Token-gated routes still resolve normally — owners with the token can
	 * still load their own test groups directly.
	 */
	public const TEST_GROUP_PREFIX = '__UX__';

	public static function is_test_group( int $group_id ): bool {
		return str_starts_with( (string) get_the_title( $group_id ), self::TEST_GROUP_PREFIX );
	}

	/**
	 * Cross-group leaderboard for a competition: aggregates points per (user, group)
	 * pair, returned sorted desc. Drives the public /pronostico/<competition> view.
	 */
	public static function competition_leaderboard( string $competition_id, int $limit = 50 ): array {
		$storage_id = Mantia_Competitions::storage_id( $competition_id );
		$group_ids  = array_values( array_filter(
			self::groups_in_competition( $storage_id ),
			static fn ( int $gid ): bool => ! self::is_test_group( $gid )
		) );
		if ( empty( $group_ids ) ) {
			return array();
		}
		$rows = array();
		foreach ( $group_ids as $gid ) {
			foreach ( Mantia_Leaderboard::rows( $gid, 100 ) as $r ) {
				$rows[] = array_merge(
					$r,
					array(
						'group_id'   => $gid,
						'group_name' => get_the_title( $gid ),
					)
				);
			}
		}
		usort(
			$rows,
			static fn ( array $a, array $b ): int => ( $b['points'] <=> $a['points'] )
				?: ( $b['exacts'] <=> $a['exacts'] )
				?: strcasecmp( $a['name'], $b['name'] )
		);
		$out = array_slice( $rows, 0, max( 1, $limit ) );
		foreach ( $out as $i => &$row ) {
			$row['rank'] = $i + 1;
		}
		return $out;
	}

	public static function groups_in_competition( string $competition_id ): array {
		$posts = get_posts(
			array(
				'post_type'      => Mantia_CPTs::GROUP,
				'post_status'    => 'publish',
				'posts_per_page' => -1,
				'no_found_rows'  => true,
				'meta_key'       => Mantia_Competitions::META_KEY,
				'meta_value'     => $competition_id,
			)
		);
		return array_map( static fn ( WP_Post $p ): int => (int) $p->ID, $posts );
	}

	public static function set_group_competition( int $group_id, string $competition_id ): bool {
		if ( ! Mantia_Competitions::get( $competition_id ) ) {
			return false;
		}
		update_post_meta( $group_id, Mantia_Competitions::META_KEY, $competition_id );
		return true;
	}

	/**
	 * Download an image and stamp it as the user's avatar. Stored as
	 * META_AVATAR_ATTACHMENT_ID on the wp_user; the frontend prefers
	 * this over the generated initials avatar when present.
	 *
	 * (Previously this set a featured image on the mantia_user CPT; the
	 * wp_user backing means we store the attachment id directly in
	 * user_meta and let the frontend resolve it via wp_get_attachment_url.)
	 *
	 * @return int Attachment ID, or 0 on failure.
	 */
	public static function set_user_avatar_from_url( int $user_id, string $image_url, array $request_headers = array() ): int {
		if ( $user_id <= 0 || '' === $image_url ) {
			return 0;
		}
		// Verify the user exists in wp_users (any caller error here means
		// we'd otherwise stamp orphan meta or leak an attachment).
		if ( ! get_user_by( 'id', $user_id ) ) {
			return 0;
		}

		$response = wp_remote_get(
			$image_url,
			array(
				'timeout' => 15,
				'headers' => $request_headers, // Meta media URLs need Bearer auth
			)
		);
		if ( is_wp_error( $response ) || 200 !== (int) wp_remote_retrieve_response_code( $response ) ) {
			return 0;
		}

		$body         = (string) wp_remote_retrieve_body( $response );
		$content_type = (string) wp_remote_retrieve_header( $response, 'content-type' );
		$ext          = self::guess_extension_from_content_type( $content_type );
		if ( '' === $ext ) {
			return 0;
		}

		require_once ABSPATH . 'wp-admin/includes/file.php';
		require_once ABSPATH . 'wp-admin/includes/image.php';
		require_once ABSPATH . 'wp-admin/includes/media.php';

		$tmp = wp_tempnam( 'mantia-avatar-' . $user_id . '.' . $ext );
		if ( false === file_put_contents( $tmp, $body ) ) {
			return 0;
		}

		$attachment_id = media_handle_sideload(
			array(
				'name'     => sprintf( 'avatar-%d-%d.%s', $user_id, time(), $ext ),
				'tmp_name' => $tmp,
				'size'     => strlen( $body ),
				'type'     => $content_type,
			),
			0, // No parent post — orphan attachments are fine for avatars.
			sprintf( 'Avatar for mantia user %d', $user_id )
		);
		if ( is_wp_error( $attachment_id ) ) {
			@unlink( $tmp );
			return 0;
		}

		update_user_meta( $user_id, self::META_AVATAR_ATTACHMENT_ID, (int) $attachment_id );
		return (int) $attachment_id;
	}

	public const META_AVATAR_ATTACHMENT_ID = '_mantia_avatar_attachment_id';

	/** Return the URL for the user's uploaded avatar, or '' if none set. */
	public static function user_avatar_url( int $user_id ): string {
		$attachment_id = (int) get_user_meta( $user_id, self::META_AVATAR_ATTACHMENT_ID, true );
		if ( $attachment_id <= 0 ) {
			return '';
		}
		return (string) wp_get_attachment_url( $attachment_id );
	}

	private static function guess_extension_from_content_type( string $content_type ): string {
		$content_type = strtolower( trim( explode( ';', $content_type )[0] ) );
		return match ( $content_type ) {
			'image/jpeg', 'image/jpg' => 'jpg',
			'image/png'               => 'png',
			'image/webp'              => 'webp',
			'image/gif'               => 'gif',
			default                   => '',
		};
	}

	/**
	 * Return every user post that has $group_id in its META_GROUP_IDS.
	 * Penca scale is small (<100 members), so full-table scan over the
	 * user CPT is fine and saves us a serialized-meta LIKE hack.
	 *
	 * @return array<int, array{id:int,name:string,phone:string,display_name:string}>
	 */
	public static function group_members( int $group_id ): array {
		if ( $group_id <= 0 ) {
			return array();
		}
		// Query wp_users that have this group_id in their META_GROUP_IDS.
		// get_users meta_query handles the serialized-array LIKE match via
		// the 'compare' => 'LIKE' fallback — fine at our scale (<100 members).
		$users = get_users( array(
			'meta_query' => array(
				array(
					'key'     => self::META_GROUP_IDS,
					'value'   => sprintf( 'i:%d;', (int) $group_id ),
					'compare' => 'LIKE',
				),
			),
			'fields'     => 'all',
			'number'     => -1,
		) );
		$members = array();
		foreach ( $users as $u ) {
			// Double-check the LIKE match wasn't a false positive (e.g.
			// group 12 substring-matching group 123). The serialized
			// fragment 'i:12;' is unique within array values but better
			// to verify properly.
			$groups = (array) get_user_meta( (int) $u->ID, self::META_GROUP_IDS, true );
			if ( ! in_array( $group_id, array_map( 'intval', $groups ), true ) ) {
				continue;
			}
			$name  = (string) $u->display_name;
			$phone = (string) get_user_meta( (int) $u->ID, self::META_PHONE, true );
			// display_name comes from WhatsApp profile.name (refreshed by
			// the bridge on every inbound). Without a real name (privacy-
			// locked profile, or user joined before profile.name capture),
			// fall back to the formatted phone — easier for humans to match
			// against contacts than a generic "Jugador".
			$has_name = '' !== $name && $name !== $phone && $name !== '+' . $phone;
			if ( $has_name ) {
				$display = $name;
			} elseif ( '' !== $phone ) {
				$display = self::format_phone_for_display( $phone );
			} else {
				$display = __( 'Jugador', 'mantia' );
			}
			$members[] = array(
				'id'           => (int) $u->ID,
				'name'         => $name,
				'phone'        => $phone,
				'display_name' => $display,
			);
		}
		usort(
			$members,
			static fn( array $a, array $b ): int => strcasecmp( (string) $a['display_name'], (string) $b['display_name'] )
		);
		return $members;
	}

	/**
	 * Return the user's group IDs that belong to a given competition. A
	 * "match" here is at storage_id level: a group in libertadores-semana
	 * (a view) is considered a match for any match in libertadores-2026
	 * (its parent), because the window-views never store matches of their
	 * own — they're just filtered windows over the parent.
	 *
	 * @return array<int,int>
	 */
	public static function user_groups_in_competition( int $user_id, string $competition_id ): array {
		$target = Mantia_Competitions::storage_id( $competition_id );
		$out    = array();
		foreach ( self::user_groups_to_array( $user_id ) as $g ) {
			$group_comp = (string) ( $g['competition_id'] ?? '' );
			$group_root = Mantia_Competitions::storage_id( $group_comp );
			if ( $group_root === $target ) {
				$out[] = (int) $g['id'];
			}
		}
		return $out;
	}

	public static function generate_invite_code( string $name ): string {
		$base = self::normalize_invite_code( $name );
		$base = '' !== $base ? substr( $base, 0, 14 ) : 'MANTIA';

		for ( $attempt = 0; $attempt < 10; ++$attempt ) {
			$suffix = strtoupper( substr( wp_generate_password( 5, false, false ), 0, 5 ) );
			$code   = self::normalize_invite_code( $base . $suffix );
			if ( ! self::find_group_by_invite_code( $code ) ) {
				return $code;
			}
		}

		return self::normalize_invite_code( $base . wp_rand( 10000, 99999 ) );
	}

	public static function find_group_by_invite_code( string $invite_code ): ?WP_Post {
		$invite_code = self::normalize_invite_code( $invite_code );
		if ( '' === $invite_code ) {
			return null;
		}

		$posts = get_posts(
			array(
				'post_type'      => Mantia_CPTs::GROUP,
				'post_status'    => 'publish',
				'posts_per_page' => 1,
				'no_found_rows'  => true,
				'meta_key'       => self::META_INVITE_CODE,
				'meta_value'     => $invite_code,
			)
		);

		return $posts[0] ?? null;
	}

	public static function find_group_by_invite_message( string $message ): ?WP_Post {
		$code = self::extract_invite_code_from_message( $message );
		return '' !== $code ? self::find_group_by_invite_code( $code ) : null;
	}

	public static function extract_invite_code_from_message( string $message ): string {
		$message = trim( $message );
		if ( '' === $message ) {
			return '';
		}

		// 1. Single token (the user pasted just the code).
		if ( ! str_contains( $message, ' ' ) && ! str_contains( $message, "\n" ) && ! str_contains( $message, "\t" ) ) {
			$code = self::normalize_invite_code( $message );
			return strlen( $code ) >= 4 ? $code : '';
		}

		$plain = function_exists( 'remove_accents' ) ? remove_accents( $message ) : $message;

		// 2. Conversational forms with the code at the end after a separator
		//    e.g. "Hola, me quiero sumar a Penca Familia · CODE".
		if ( preg_match( '/[·•|\-]\s+([A-Za-z0-9_-]{4,32})\s*$/u', $message, $matches ) ) {
			$code = self::normalize_invite_code( (string) $matches[1] );
			if ( strlen( $code ) >= 4 ) {
				return $code;
			}
		}

		// 3. Command-prefix forms — keeps the older patterns + adds "sumar"
		//    so wa.me prefills like "sumar CODE" route correctly.
		if ( preg_match(
			'/^\s*(?:codigo|grupo|penca|invite|invitacion|sumar(?:me)?|me\s+sumo(?:\s+a)?|me\s+quiero\s+sumar(?:\s+a)?|me\s+uno(?:\s+a)?|unirme(?:\s+a)?)\s*[:#\-·]?\s+([A-Za-z0-9_-]{4,32})\s*$/i',
			(string) $plain,
			$matches
		) ) {
			return self::normalize_invite_code( (string) $matches[1] );
		}

		return '';
	}

	public static function default_group_id(): int {
		return self::create_group( __( 'Liga Uruguay', 'mantia' ), 'URUGUAY2026', 'liga-uruguay' );
	}

	public static function join_group( string $phone, string $invite_code, string $name = '', string $recipient = '' ): array|WP_Error {
		$group = self::find_group_by_invite_code( $invite_code );
		if ( ! $group ) {
			return new WP_Error( 'mantia_group_not_found', __( 'No encuentro ese codigo de grupo.', 'mantia' ) );
		}

		$user_id = self::get_or_create_user( $phone, $name, $recipient );
		if ( 0 === $user_id ) {
			return new WP_Error( 'mantia_invalid_phone', __( 'Necesito un telefono valido para unirte al grupo.', 'mantia' ) );
		}

		$groups = self::user_group_ids( $user_id );
		$already_member = in_array( (int) $group->ID, $groups, true );
		if ( ! $already_member ) {
			$groups[] = (int) $group->ID;
			update_user_meta( $user_id, self::META_GROUP_IDS, array_values( $groups ) );
		}
		update_user_meta( $user_id, self::META_ACTIVE_GROUP_ID, (int) $group->ID );

		// Auto-fill predictions for every upcoming match in this penca's
		// competition. Keeps users "in the game" the second they join —
		// they can override any score before kickoff, but they don't have
		// to predict every match manually to appear on the leaderboard.
		// Filter `mantia_auto_predict_on_join` (default true) flips it off
		// for installs that want to enforce manual-only predictions.
		$autofilled = 0;
		if ( ! $already_member && apply_filters( 'mantia_auto_predict_on_join', true, $user_id, (int) $group->ID ) ) {
			$autofilled = self::auto_fill_predictions( $user_id, (int) $group->ID );
		}

		return array(
			'user_id'        => $user_id,
			'group_id'       => (int) $group->ID,
			'already_member' => $already_member,
			'active_group'   => (int) $group->ID,
			'group'          => self::group_to_array( (int) $group->ID ),
			'autofilled'     => $autofilled,
		);
	}

	/**
	 * Seed predictions for every upcoming match in the group's competition
	 * that this user doesn't have one for yet.
	 *
	 * If the user has already predicted the same match in another penca
	 * (same competition, different group), we copy that score instead of
	 * generating a fresh random — consistent with the WhatsApp fan-out
	 * behavior where one prediction spans every penca in the competition.
	 *
	 * Returns the number of predictions created (skipped ones don't count).
	 */
	public static function auto_fill_predictions( int $user_id, int $group_id ): int {
		$competition_id = self::group_competition_id( $group_id );
		if ( '' === $competition_id ) {
			return 0;
		}

		// Wide window: cover the entire Mundial (1 year is plenty of
		// headroom for any pool we care about — group stage starts
		// 11 jun, final ~19 jul). The repository's "upcoming" filter
		// already drops finished matches.
		$matches = self::upcoming_matches_for_competition( $competition_id, 24 * 365 );
		if ( empty( $matches ) ) {
			return 0;
		}

		$created = 0;
		foreach ( $matches as $match ) {
			$match_id = (int) $match['id'];
			if ( self::find_prediction( $user_id, $match_id, $group_id ) ) {
				continue;
			}

			$existing = self::find_existing_user_match_scores( $user_id, $match_id, $group_id );
			if ( $existing ) {
				$scores = $existing;
			} else {
				// Strength-aware random: heavy favorites get higher expected
				// goals, so Argentina vs Tunisia auto-fills closer to 2-0 than
				// 1-1, while Uruguay vs Portugal hovers near the realistic
				// "any of three results" middle.
				$home_str = self::team_strength( (string) $match['home_team'] );
				$away_str = self::team_strength( (string) $match['away_team'] );
				$scores   = self::random_realistic_score( $home_str, $away_str );
			}

			$pred = self::register_prediction(
				$user_id,
				$match_id,
				$group_id,
				(int) $scores[0],
				(int) $scores[1],
				true // auto_filled — let /me/ surface the "still random" hint.
			);
			if ( ! is_wp_error( $pred ) ) {
				$created++;
			}
		}
		return $created;
	}

	/**
	 * Look across all of the user's other groups for a prior prediction
	 * on the same match. Returns [home, away] or null when there isn't one.
	 *
	 * The $skip_group_id parameter avoids picking up the empty slot we're
	 * about to fill in the caller's group.
	 */
	private static function find_existing_user_match_scores( int $user_id, int $match_id, int $skip_group_id ): ?array {
		foreach ( self::user_group_ids( $user_id ) as $gid ) {
			$gid = (int) $gid;
			if ( $gid === $skip_group_id ) {
				continue;
			}
			$pred = self::find_prediction( $user_id, $match_id, $gid );
			if ( $pred ) {
				return array(
					(int) get_post_meta( (int) $pred->ID, self::META_PRED_HOME_SCORE, true ),
					(int) get_post_meta( (int) $pred->ID, self::META_PRED_AWAY_SCORE, true ),
				);
			}
		}
		return null;
	}

	/**
	 * Return a [home, away] score drawn from a realistic football
	 * distribution. Each team's expected goal output scales with its
	 * `team_strength()` rating (1..10): two perfect-balanced teams
	 * average ~1.3 goals each, an Argentina-vs-Tunisia mismatch lands
	 * closer to ~2.5 vs ~0.5. Scores are sampled independently with a
	 * Poisson process, clamped at 6, so we never produce nonsense like
	 * 9-7. Tests that need determinism can `mt_srand(...)` first.
	 *
	 * @param int|null $home_strength 1..10, or null for neutral (5).
	 * @param int|null $away_strength 1..10, or null for neutral (5).
	 * @return array{0:int,1:int}
	 */
	public static function random_realistic_score( ?int $home_strength = null, ?int $away_strength = null ): array {
		$home_strength = max( 1, min( 10, $home_strength ?? 5 ) );
		$away_strength = max( 1, min( 10, $away_strength ?? 5 ) );

		// Expected goals tuned so the strength=5/5 baseline produces a
		// distribution close to a real World Cup (mean ~1.3 goals/side,
		// most common scoreline 1-1, then 1-0/0-1).
		$lambda_h = $home_strength * 0.26;
		$lambda_a = $away_strength * 0.26;

		return array( self::poisson_sample( $lambda_h ), self::poisson_sample( $lambda_a ) );
	}

	/**
	 * Knuth's straightforward Poisson sampler. Sufficient for the small
	 * lambdas (~0.3..2.6) we use here — no need to pull in a stats lib.
	 * Clamps the result at 6 because anything higher in a single half is
	 * a freak event that auto-fill shouldn't seed.
	 */
	private static function poisson_sample( float $lambda ): int {
		$l = exp( -$lambda );
		$k = 0;
		$p = 1.0;
		do {
			$k++;
			$p *= mt_rand() / mt_getrandmax();
		} while ( $p > $l );
		return max( 0, min( 6, $k - 1 ) );
	}

	/**
	 * Team strength on a 1..10 scale, hand-curated from late-2025 FIFA
	 * rankings for the 48 Mundial 2026 sides. Unknown teams fall back to
	 * 5 (neutral) so auto-fill behaves gracefully for friendlies or
	 * non-Mundial competitions that may share the fixture system later.
	 *
	 * The table is intentionally short — there's no point feeding the
	 * decimal-precision FIFA points into a Poisson sampler that only
	 * cares about ballpark gap. If a team moves a tier, edit it here.
	 *
	 * Filter `mantia_team_strength` lets a site override per-team or
	 * supply a different competition (e.g. Libertadores) without
	 * forking the table.
	 */
	public static function team_strength( string $team ): int {
		static $table = array(
			// Tier 10 — top contenders.
			'Argentina' => 10,
			'Francia' => 10,
			'España' => 10,
			'Brasil' => 10,
			// Tier 9 — strong favourites.
			'Inglaterra' => 9,
			'Alemania' => 9,
			'Portugal' => 9,
			'Países Bajos' => 9,
			// Tier 8 — dark horses.
			'Italia' => 8,
			'Bélgica' => 8,
			'Croacia' => 8,
			'Marruecos' => 8,
			'Uruguay' => 8,
			'Colombia' => 8,
			'México' => 8,
			// Tier 7 — solid mid-pack.
			'Suiza' => 7,
			'Dinamarca' => 7,
			'Senegal' => 7,
			'Estados Unidos' => 7,
			'Japón' => 7,
			'Corea del Sur' => 7,
			'Polonia' => 7,
			'Australia' => 7,
			'Ecuador' => 7,
			'Serbia' => 7,
			// Tier 6 — competitive minnows.
			'Irán' => 6,
			'Túnez' => 6,
			'Canadá' => 6,
			'Costa de Marfil' => 6,
			'Egipto' => 6,
			'Argelia' => 6,
			'Paraguay' => 6,
			'Perú' => 6,
			'Chile' => 6,
			'Venezuela' => 6,
			// Tier 5 — guests / qualifiers expected to struggle.
			'Bolivia' => 5,
			'Honduras' => 5,
			'Panamá' => 5,
			'Jamaica' => 5,
			'Arabia Saudí' => 5,
			'Catar' => 5,
			'Sudáfrica' => 5,
			// Tier 4 — heavy underdogs.
			'Nueva Zelanda' => 4,
			'Curazao' => 4,
			'El Salvador' => 4,
			'Haití' => 4,
		);

		$rating = $table[ $team ] ?? 5;
		return (int) apply_filters( 'mantia_team_strength', $rating, $team );
	}

	public static function user_group_ids( int $user_id ): array {
		$groups = get_user_meta( $user_id, self::META_GROUP_IDS, true );
		if ( ! is_array( $groups ) ) {
			return array();
		}

		return array_values( array_unique( array_map( 'intval', $groups ) ) );
	}

	public static function active_group_id_for_user( int $user_id ): int {
		$active = (int) get_user_meta( $user_id, self::META_ACTIVE_GROUP_ID, true );
		if ( $active > 0 ) {
			return $active;
		}

		$groups = self::user_group_ids( $user_id );
		if ( ! empty( $groups ) ) {
			return (int) $groups[0];
		}

		return 0;
	}

	public static function set_active_group_for_user( int $user_id, int $group_id ): array|WP_Error {
		if ( $group_id <= 0 || Mantia_CPTs::GROUP !== get_post_type( $group_id ) ) {
			return new WP_Error( 'mantia_group_not_found', __( 'No encuentro ese grupo.', 'mantia' ) );
		}

		$groups = self::user_group_ids( $user_id );
		if ( ! in_array( $group_id, $groups, true ) ) {
			return new WP_Error( 'mantia_group_not_joined', __( 'Todavia no estas en ese grupo. Mandame el codigo de invitacion para unirte.', 'mantia' ) );
		}

		update_user_meta( $user_id, self::META_ACTIVE_GROUP_ID, $group_id );

		return array(
			'user_id'      => $user_id,
			'active_group' => self::group_to_array( $group_id ),
			'groups'       => self::user_groups_to_array( $user_id ),
		);
	}

	public static function user_groups_to_array( int $user_id ): array {
		$active = self::active_group_id_for_user( $user_id );

		return array_map(
			static function ( int $group_id ) use ( $active ): array {
				$group              = self::group_to_array( $group_id );
				$group['is_active'] = $group_id === $active;
				return $group;
			},
			self::user_group_ids( $user_id )
		);
	}

	public static function group_invite_message( int $group_id ): string {
		$group = self::group_to_array( $group_id );
		if ( empty( $group ) ) {
			return '';
		}

		return sprintf(
			'Para sumarte a %s, mandale este codigo al bot de WhatsApp: %s',
			$group['name'],
			$group['invite_code']
		);
	}

	public static function upsert_match( array $match ): int {
		$external_id = sanitize_key( (string) ( $match['external_id'] ?? '' ) );
		if ( '' === $external_id ) {
			return 0;
		}

		$post = self::find_match_by_external_id( $external_id );
		$data = array(
			'post_type'   => Mantia_CPTs::MATCH,
			'post_status' => 'publish',
			'post_title'  => self::match_title( (string) $match['home_team'], (string) $match['away_team'] ),
		);

		if ( $post ) {
			$data['ID'] = $post->ID;
			$post_id    = wp_update_post( $data, true );
		} else {
			$post_id = wp_insert_post( $data, true );
		}

		if ( is_wp_error( $post_id ) ) {
			return 0;
		}

		$post_id = (int) $post_id;
		$kickoff = self::parse_gmt_timestamp( (string) ( $match['kickoff_gmt'] ?? '' ) );

		update_post_meta( $post_id, self::META_EXTERNAL_ID, $external_id );
		update_post_meta( $post_id, self::META_HOME_TEAM, sanitize_text_field( (string) ( $match['home_team'] ?? '' ) ) );
		update_post_meta( $post_id, self::META_AWAY_TEAM, sanitize_text_field( (string) ( $match['away_team'] ?? '' ) ) );
		update_post_meta( $post_id, self::META_KICKOFF_GMT, gmdate( 'Y-m-d H:i:s', $kickoff ) );
		update_post_meta( $post_id, self::META_KICKOFF_TS, $kickoff );
		update_post_meta( $post_id, self::META_PHASE, sanitize_text_field( (string) ( $match['phase'] ?? '' ) ) );
		update_post_meta( $post_id, self::META_STATUS, sanitize_key( (string) ( $match['status'] ?? 'scheduled' ) ) );
		update_post_meta( $post_id, self::META_HOME_SCORE, isset( $match['home_score'] ) ? (int) $match['home_score'] : '' );
		update_post_meta( $post_id, self::META_AWAY_SCORE, isset( $match['away_score'] ) ? (int) $match['away_score'] : '' );
		update_post_meta( $post_id, self::META_RESOLVED, ! empty( $match['resolved'] ) ? 1 : 0 );

		$competition_id = isset( $match['competition_id'] ) && Mantia_Competitions::get( (string) $match['competition_id'] )
			? (string) $match['competition_id']
			: Mantia_Competitions::default_id();
		update_post_meta( $post_id, Mantia_Competitions::META_KEY, $competition_id );

		return $post_id;
	}

	public static function find_match_by_external_id( string $external_id ): ?WP_Post {
		$posts = get_posts(
			array(
				'post_type'      => Mantia_CPTs::MATCH,
				'post_status'    => 'any',
				'posts_per_page' => 1,
				'no_found_rows'  => true,
				'meta_key'       => self::META_EXTERNAL_ID,
				'meta_value'     => sanitize_key( $external_id ),
			)
		);

		return $posts[0] ?? null;
	}

	public static function match_to_array( int $match_id ): array {
		$post = get_post( $match_id );
		if ( ! $post || Mantia_CPTs::MATCH !== $post->post_type ) {
			return array();
		}

		$comp_id = (string) get_post_meta( $match_id, Mantia_Competitions::META_KEY, true );
		if ( '' === $comp_id ) {
			$comp_id = Mantia_Competitions::default_id();
		}

		return array(
			'id'             => $match_id,
			'external_id'    => (string) get_post_meta( $match_id, self::META_EXTERNAL_ID, true ),
			'home_team'      => (string) get_post_meta( $match_id, self::META_HOME_TEAM, true ),
			'away_team'      => (string) get_post_meta( $match_id, self::META_AWAY_TEAM, true ),
			'kickoff_gmt'    => (string) get_post_meta( $match_id, self::META_KICKOFF_GMT, true ),
			'kickoff_ts'     => (int) get_post_meta( $match_id, self::META_KICKOFF_TS, true ),
			'phase'          => (string) get_post_meta( $match_id, self::META_PHASE, true ),
			'status'         => (string) get_post_meta( $match_id, self::META_STATUS, true ),
			'home_score'     => self::nullable_int_meta( $match_id, self::META_HOME_SCORE ),
			'away_score'     => self::nullable_int_meta( $match_id, self::META_AWAY_SCORE ),
			'resolved'       => (bool) get_post_meta( $match_id, self::META_RESOLVED, true ),
			'competition_id' => $comp_id,
		);
	}

	public static function group_to_array( int $group_id ): array {
		$post = get_post( $group_id );
		if ( ! $post || Mantia_CPTs::GROUP !== $post->post_type ) {
			return array();
		}

		$name      = get_the_title( $group_id );
		$code      = (string) get_post_meta( $group_id, self::META_INVITE_CODE, true );
		$share_url = self::build_share_url( $code, (string) $name );
		$comp_id   = self::group_competition_id( $group_id );
		$comp      = Mantia_Competitions::get( $comp_id );

		$invite_message  = sprintf( 'Sumate a %s. Tocá el link y enviá: %s', $name, $share_url );
		$invite_fallback = '' === $share_url
			? sprintf( 'Sumate a %s. Mandale este codigo al bot de WhatsApp: %s', $name, $code )
			: $invite_message;

		return array(
			'id'               => $group_id,
			'name'             => $name,
			'invite_code'      => $code,
			'share_url'        => $share_url,
			'view_url'         => self::group_view_url( $group_id ),
			'invite_message'   => $invite_fallback,
			'slug'             => (string) get_post_meta( $group_id, self::META_GROUP_SLUG, true ),
			'competition_id'   => $comp_id,
			'competition_name' => $comp ? trim( ( $comp['emoji'] ?? '' ) . ' ' . $comp['name'] ) : $comp_id,
		);
	}

	/**
	 * Build a magic-link URL to a group's web view, scoped to a specific
	 * user (so the click auto-logs them in). Path is /pronostico/g/<slug>/ —
	 * stable + cacheable, no token in the visible URL after redemption.
	 *
	 * If $user_id is 0 (workflow callers, public previews), falls back to
	 * the slug-only path with no auth — the public preview pages still
	 * render but in anonymous mode.
	 */
	public static function group_view_url( int $group_id, int $for_user_id = 0 ): string {
		$slug = (string) get_post_meta( $group_id, self::META_GROUP_SLUG, true );
		if ( '' === $slug ) {
			$slug = (string) sanitize_title( (string) get_the_title( $group_id ) );
		}
		$path = '/pronostico/g/' . $slug . '/';
		if ( $for_user_id <= 0 ) {
			return home_url( $path );
		}
		$user = get_user_by( 'id', $for_user_id );
		if ( ! $user ) {
			return home_url( $path );
		}
		$phone = (string) get_user_meta( $for_user_id, self::META_PHONE, true );
		$url = WA_Identity_Bridge::sign_link(
			array( 'phone' => $phone, 'name' => $user->display_name ),
			$path
		);
		return '' !== $url ? $url : home_url( $path );
	}

	/**
	 * Magic-link to the user's own /pronostico/me/ page. Requires $user_id —
	 * /pronostico/me/ is auth-gated and has no anonymous preview.
	 */
	public static function user_view_url( int $user_id ): string {
		$user = get_user_by( 'id', $user_id );
		if ( ! $user ) {
			return '';
		}
		$phone = (string) get_user_meta( $user_id, self::META_PHONE, true );
		$url = WA_Identity_Bridge::sign_link(
			array( 'phone' => $phone, 'name' => $user->display_name ),
			'/pronostico/me/'
		);
		return $url;
	}

	public static function competition_view_url( string $competition_id ): string {
		return home_url( '/pronostico/' . $competition_id );
	}

	public static function bot_phone_e164(): string {
		$value = (string) get_option( 'mantia_bot_phone_e164', '' );
		return preg_replace( '/\D+/', '', $value ) ?: '';
	}

	/**
	 * Build a wa.me deeplink whose prefilled text looks like a real
	 * message — "Hola, me quiero sumar a <Penca> · <CODE>" — so the
	 * recipient sees a coherent message in their compose box and can
	 * just hit send. The bot's extract_invite_code_from_message still
	 * recovers the code from this form.
	 */
	public static function build_share_url( string $invite_code, string $group_name = '' ): string {
		$invite_code = self::normalize_invite_code( $invite_code );
		$bot_phone   = self::bot_phone_e164();
		if ( '' === $invite_code || '' === $bot_phone ) {
			return '';
		}
		$text = '' !== $group_name
			? sprintf( 'Hola, me quiero sumar a %s · %s', $group_name, $invite_code )
			: sprintf( 'sumar %s', $invite_code );
		return sprintf( 'https://wa.me/%s?text=%s', $bot_phone, rawurlencode( $text ) );
	}

	public static function upcoming_matches( int $hours_ahead = 48 ): array {
		return self::upcoming_matches_for_competition( '', $hours_ahead );
	}

	public static function upcoming_matches_for_competition( string $competition_id, int $hours_ahead = 48 ): array {
		$now = time();

		// Views like `libertadores-semana` are stored as `libertadores-2026`
		// and apply a tighter time window. Honor both: cap hours_ahead by the
		// view's window_days, then query against the storage id.
		$window_days = '' !== $competition_id ? Mantia_Competitions::window_days( $competition_id ) : 0;
		if ( $window_days > 0 ) {
			$hours_ahead = min( $hours_ahead, $window_days * 24 );
		}
		$storage_id = '' !== $competition_id ? Mantia_Competitions::storage_id( $competition_id ) : '';

		$max = $now + max( 1, $hours_ahead ) * HOUR_IN_SECONDS;

		$meta_query = array(
			array(
				'key'     => self::META_STATUS,
				'value'   => 'scheduled',
				'compare' => '=',
			),
			array(
				'key'     => self::META_KICKOFF_TS,
				'value'   => array( $now, $max ),
				'compare' => 'BETWEEN',
				'type'    => 'NUMERIC',
			),
		);

		if ( '' !== $storage_id ) {
			$meta_query[] = array(
				'key'   => Mantia_Competitions::META_KEY,
				'value' => $storage_id,
			);
		}

		return array_map(
			static fn ( WP_Post $post ): array => self::match_to_array( (int) $post->ID ),
			get_posts(
				array(
					'post_type'      => Mantia_CPTs::MATCH,
					'post_status'    => 'publish',
					'posts_per_page' => 50,
					'no_found_rows'  => true,
					'meta_key'       => self::META_KICKOFF_TS,
					'orderby'        => 'meta_value_num',
					'order'          => 'ASC',
					'meta_query'     => $meta_query,
				)
			)
		);
	}

	public static function find_next_match_for_team( string $team ): array {
		$needle = self::team_key( $team );
		if ( '' === $needle ) {
			return array();
		}

		$posts = get_posts(
			array(
				'post_type'      => Mantia_CPTs::MATCH,
				'post_status'    => 'publish',
				'posts_per_page' => 100,
				'no_found_rows'  => true,
				'meta_key'       => self::META_KICKOFF_TS,
				'orderby'        => 'meta_value_num',
				'order'          => 'ASC',
				'meta_query'     => array(
					array(
						'key'     => self::META_STATUS,
						'value'   => 'scheduled',
						'compare' => '=',
					),
					array(
						'key'     => self::META_KICKOFF_TS,
						'value'   => time(),
						'compare' => '>',
						'type'    => 'NUMERIC',
					),
				),
			)
		);

		foreach ( $posts as $post ) {
			$match = self::match_to_array( (int) $post->ID );
			if ( $needle === self::team_key( $match['home_team'] ) || $needle === self::team_key( $match['away_team'] ) ) {
				return $match;
			}
		}

		return array();
	}

	public static function find_next_match_between( string $first_team, string $second_team ): array {
		$first  = self::team_key( $first_team );
		$second = self::team_key( $second_team );
		if ( '' === $first || '' === $second ) {
			return array();
		}

		$posts = get_posts(
			array(
				'post_type'      => Mantia_CPTs::MATCH,
				'post_status'    => 'publish',
				'posts_per_page' => 100,
				'no_found_rows'  => true,
				'meta_key'       => self::META_KICKOFF_TS,
				'orderby'        => 'meta_value_num',
				'order'          => 'ASC',
				'meta_query'     => array(
					array(
						'key'     => self::META_STATUS,
						'value'   => 'scheduled',
						'compare' => '=',
					),
					array(
						'key'     => self::META_KICKOFF_TS,
						'value'   => time(),
						'compare' => '>',
						'type'    => 'NUMERIC',
					),
				),
			)
		);

		foreach ( $posts as $post ) {
			$match = self::match_to_array( (int) $post->ID );
			$home  = self::team_key( $match['home_team'] );
			$away  = self::team_key( $match['away_team'] );
			if ( ( $first === $home && $second === $away ) || ( $first === $away && $second === $home ) ) {
				return $match;
			}
		}

		return array();
	}

	public static function team_key_for_match( string $team ): string {
		return self::team_key( $team );
	}

	/**
	 * Upsert a prediction.
	 *
	 * @param bool $auto_filled true when the call originates in
	 *   auto_fill_predictions() — sets META_AUTO_FILLED so the /me/
	 *   page can show "your scores are still random" hints. Callers
	 *   from the user-initiated path (WhatsApp parsing, REST endpoint)
	 *   should leave the default false; the upsert clears any prior
	 *   auto-fill flag so editing an auto-fill PR converts it to manual.
	 */
	public static function register_prediction( int $user_id, int $match_id, int $group_id, int $home_score, int $away_score, bool $auto_filled = false ): array|WP_Error {
		$match = self::match_to_array( $match_id );
		if ( empty( $match ) ) {
			return new WP_Error( 'mantia_match_not_found', __( 'No encuentro ese partido.', 'mantia' ) );
		}
		// Predictions lock $lockout seconds before kickoff (default 10 min)
		// so a user typing "2-1" at the 60-second mark doesn't race the
		// match start. Tournament admins can shorten via the filter.
		$lockout = (int) apply_filters( 'mantia_prediction_lockout_seconds', 600 );
		if ( 'scheduled' !== $match['status'] || (int) $match['kickoff_ts'] <= ( time() + max( 0, $lockout ) ) ) {
			// Distinguish the two cases — "already finished" vs "too late to
			// edit before kickoff" — so the bot reply matches what the user
			// actually saw (the match might not even have started yet).
			$msg = ( 'scheduled' !== $match['status'] )
				? __( 'Ese partido ya cerró para pronósticos.', 'mantia' )
				: __( 'Ese partido cierra para pronósticos antes del arranque. Ya no se puede cambiar.', 'mantia' );
			return new WP_Error( 'mantia_match_closed', $msg );
		}

		$existing = self::find_prediction( $user_id, $match_id, $group_id );
		$title    = sprintf(
			'%s: %s %d-%d %s',
			self::user_display_name( $user_id ),
			$match['home_team'],
			$home_score,
			$away_score,
			$match['away_team']
		);
		$postarr  = array(
			'post_type'   => Mantia_CPTs::PREDICTION,
			'post_status' => 'publish',
			'post_title'  => $title,
		);

		if ( $existing ) {
			$postarr['ID'] = $existing->ID;
			$post_id       = wp_update_post( $postarr, true );
		} else {
			$post_id = wp_insert_post( $postarr, true );
		}

		if ( is_wp_error( $post_id ) ) {
			return $post_id;
		}

		$post_id = (int) $post_id;
		update_post_meta( $post_id, self::META_USER_ID, $user_id );
		update_post_meta( $post_id, self::META_USER_PHONE, (string) get_user_meta( $user_id, self::META_PHONE, true ) );
		update_post_meta( $post_id, self::META_MATCH_ID, $match_id );
		update_post_meta( $post_id, self::META_GROUP_ID, $group_id );
		// Clamp scores to a sane range. Negative gets coerced to 0; the
		// upper bound caps absurd values (record FIFA scoreline is 31-0)
		// so an injection or fat-finger can't store 9999 and trip downstream
		// integer overflow / point-multiplier paths. Filter for tournaments
		// that need a higher cap (highly unlikely).
		$score_cap = (int) apply_filters( 'mantia_max_score', 50 );
		update_post_meta( $post_id, self::META_PRED_HOME_SCORE, max( 0, min( $score_cap, $home_score ) ) );
		update_post_meta( $post_id, self::META_PRED_AWAY_SCORE, max( 0, min( $score_cap, $away_score ) ) );
		update_post_meta( $post_id, self::META_SCORED, 0 );
		// Track origin so /me/ can tell "this user has never edited"
		// from "this user has actively predicted". Manual upserts
		// (default $auto_filled = false) clear any prior auto flag.
		update_post_meta( $post_id, self::META_AUTO_FILLED, $auto_filled ? 1 : 0 );

		return self::prediction_to_array( $post_id );
	}

	/**
	 * Has this user EVER manually predicted anything? True when at
	 * least one of their prediction rows lacks the META_AUTO_FILLED
	 * flag (or has it set to 0). Drives the "your scores are still
	 * random" hint on /me/.
	 */
	public static function user_has_manual_prediction( int $user_id ): bool {
		$found = get_posts(
			array(
				'post_type'      => Mantia_CPTs::PREDICTION,
				'post_status'    => 'publish',
				'posts_per_page' => 1,
				'no_found_rows'  => true,
				'fields'         => 'ids',
				'meta_query'     => array(
					'relation' => 'AND',
					array( 'key' => self::META_USER_ID, 'value' => $user_id ),
					array(
						'relation' => 'OR',
						array( 'key' => self::META_AUTO_FILLED, 'value' => '0' ),
						array( 'key' => self::META_AUTO_FILLED, 'compare' => 'NOT EXISTS' ),
					),
				),
			)
		);
		return ! empty( $found );
	}

	/**
	 * How many points did this user earn from the most recently
	 * finished match in $competition_id (in this $group_id's
	 * leaderboard)? Returns null when there's no finished match yet,
	 * so /me/ can skip the delta line entirely instead of saying
	 * "ganaste 0 pts" with nothing to reference.
	 *
	 * @return array{points:int, match:array}|null
	 */
	public static function last_match_delta( int $user_id, int $group_id ): ?array {
		$competition_id = self::group_competition_id( $group_id );
		$recent         = self::recent_finished_matches_for_competition( $competition_id, 1 );
		if ( empty( $recent ) ) {
			return null;
		}
		$match = $recent[0];
		$pred  = self::find_prediction( $user_id, (int) $match['id'], $group_id );
		$pts   = $pred ? (int) get_post_meta( (int) $pred->ID, self::META_POINTS, true ) : 0;
		return array( 'points' => $pts, 'match' => $match );
	}

	/**
	 * Most recently kicked-off matches for a competition, ordered by
	 * kickoff descending. Used by the consensus command — we want the
	 * one most likely to be the conversation topic.
	 */
	public static function recent_finished_matches_for_competition( string $competition_id, int $limit = 10 ): array {
		$storage_id = Mantia_Competitions::storage_id( $competition_id );
		$posts      = get_posts(
			array(
				'post_type'      => Mantia_CPTs::MATCH,
				'post_status'    => 'publish',
				'posts_per_page' => max( 1, $limit ),
				'meta_key'       => self::META_KICKOFF_TS,
				'orderby'        => 'meta_value_num',
				'order'          => 'DESC',
				'meta_query'     => array(
					'relation' => 'AND',
					array( 'key' => Mantia_Competitions::META_KEY, 'value' => $storage_id ),
					array( 'key' => self::META_KICKOFF_TS, 'value' => time(), 'compare' => '<=', 'type' => 'NUMERIC' ),
				),
			)
		);

		$matches = array();
		foreach ( $posts as $post ) {
			$matches[] = self::match_to_array( (int) $post->ID );
		}
		return $matches;
	}

	/**
	 * Group consensus for a single match: returns a [score_key => count]
	 * map of how the penca's members predicted that match. Hard guard:
	 * returns an empty array if the match hasn't kicked off yet — the
	 * "no one sees another's predictions before kickoff" rule is enforced
	 * here (callers don't have to remember).
	 *
	 * Score keys are formatted "H-A" so the caller can render them flat
	 * ("2-1: 4 jugadores") without re-parsing.
	 *
	 * @return array<string,int>
	 */
	public static function group_consensus_for_match( int $group_id, int $match_id ): array {
		$match = self::match_to_array( $match_id );
		if ( empty( $match ) ) {
			return array();
		}
		// Privacy guard: predictions are private until kickoff.
		if ( (int) $match['kickoff_ts'] > time() ) {
			return array();
		}

		$predictions = get_posts(
			array(
				'post_type'      => Mantia_CPTs::PREDICTION,
				'post_status'    => 'publish',
				'posts_per_page' => -1,
				'no_found_rows'  => true,
				'meta_query'     => array(
					'relation' => 'AND',
					array( 'key' => self::META_GROUP_ID, 'value' => $group_id ),
					array( 'key' => self::META_MATCH_ID, 'value' => $match_id ),
				),
			)
		);

		$consensus = array();
		foreach ( $predictions as $pred ) {
			$home = (int) get_post_meta( (int) $pred->ID, self::META_PRED_HOME_SCORE, true );
			$away = (int) get_post_meta( (int) $pred->ID, self::META_PRED_AWAY_SCORE, true );
			$key  = sprintf( '%d-%d', $home, $away );
			$consensus[ $key ] = ( $consensus[ $key ] ?? 0 ) + 1;
		}
		// Sort by count desc so the caller can take the head row as the
		// "majority pick" without resorting.
		arsort( $consensus );
		return $consensus;
	}

	/**
	 * Per-user predictions for a match in a group, sorted by display name.
	 * Same privacy guard as group_consensus_for_match — empty pre-kickoff.
	 *
	 * Returned shape per row:
	 *   array{
	 *     user_id: int, name: string, home: int, away: int,
	 *     exact: bool, diff: bool, winner: bool
	 *   }
	 *
	 * The exact/diff/winner flags are computed against the match's REAL
	 * score when it's finished (so the bot can mark "Bob 2-1 ✓ exact").
	 * For matches that have kicked off but aren't finished yet, all flags
	 * are false (no real score to compare against).
	 *
	 * @return array<int,array<string,mixed>>
	 */
	public static function group_predictions_for_match( int $group_id, int $match_id ): array {
		$match = self::match_to_array( $match_id );
		if ( empty( $match ) ) {
			return array();
		}
		// Privacy guard: predictions are private until kickoff.
		if ( (int) $match['kickoff_ts'] > time() ) {
			return array();
		}

		$predictions = get_posts(
			array(
				'post_type'      => Mantia_CPTs::PREDICTION,
				'post_status'    => 'publish',
				'posts_per_page' => -1,
				'no_found_rows'  => true,
				'meta_query'     => array(
					'relation' => 'AND',
					array( 'key' => self::META_GROUP_ID, 'value' => $group_id ),
					array( 'key' => self::META_MATCH_ID, 'value' => $match_id ),
				),
			)
		);

		$has_real = 'finished' === (string) $match['status']
			&& null !== $match['home_score']
			&& null !== $match['away_score'];
		$real_home = $has_real ? (int) $match['home_score'] : null;
		$real_away = $has_real ? (int) $match['away_score'] : null;

		$rows = array();
		foreach ( $predictions as $pred ) {
			$uid  = (int) get_post_meta( (int) $pred->ID, self::META_USER_ID, true );
			$home = (int) get_post_meta( (int) $pred->ID, self::META_PRED_HOME_SCORE, true );
			$away = (int) get_post_meta( (int) $pred->ID, self::META_PRED_AWAY_SCORE, true );

			$exact  = false;
			$diff   = false;
			$winner = false;
			if ( $has_real ) {
				$exact = ( $home === $real_home && $away === $real_away );
				$diff  = ( ! $exact && ( $home - $away ) === ( $real_home - $real_away ) );
				// Outcome match (home win / draw / away win) without exact or diff hit.
				$pred_sign = $home <=> $away;
				$real_sign = $real_home <=> $real_away;
				$winner = ( ! $exact && ! $diff && $pred_sign === $real_sign );
			}

			$rows[] = array(
				'user_id' => $uid,
				'name'    => self::user_display_name( $uid ),
				'home'    => $home,
				'away'    => $away,
				'exact'   => $exact,
				'diff'    => $diff,
				'winner'  => $winner,
			);
		}

		usort(
			$rows,
			static fn( array $a, array $b ): int => strcasecmp( (string) $a['name'], (string) $b['name'] )
		);
		return $rows;
	}

	public static function find_prediction( int $user_id, int $match_id, int $group_id ): ?WP_Post {
		$posts = get_posts(
			array(
				'post_type'      => Mantia_CPTs::PREDICTION,
				'post_status'    => 'publish',
				'posts_per_page' => 1,
				'no_found_rows'  => true,
				'meta_query'     => array(
					array(
						'key'   => self::META_USER_ID,
						'value' => $user_id,
					),
					array(
						'key'   => self::META_MATCH_ID,
						'value' => $match_id,
					),
					array(
						'key'   => self::META_GROUP_ID,
						'value' => $group_id,
					),
				),
			)
		);

		return $posts[0] ?? null;
	}

	public static function prediction_to_array( int $prediction_id ): array {
		$post = get_post( $prediction_id );
		if ( ! $post || Mantia_CPTs::PREDICTION !== $post->post_type ) {
			return array();
		}

		return array(
			'id'          => $prediction_id,
			'user_id'     => (int) get_post_meta( $prediction_id, self::META_USER_ID, true ),
			'user_phone'  => (string) get_post_meta( $prediction_id, self::META_USER_PHONE, true ),
			'match_id'    => (int) get_post_meta( $prediction_id, self::META_MATCH_ID, true ),
			'group_id'    => (int) get_post_meta( $prediction_id, self::META_GROUP_ID, true ),
			'home_score'  => (int) get_post_meta( $prediction_id, self::META_PRED_HOME_SCORE, true ),
			'away_score'  => (int) get_post_meta( $prediction_id, self::META_PRED_AWAY_SCORE, true ),
			'points'      => (int) get_post_meta( $prediction_id, self::META_POINTS, true ),
			'reason'      => (string) get_post_meta( $prediction_id, self::META_SCORING_REASON, true ),
			'scored'      => (bool) get_post_meta( $prediction_id, self::META_SCORED, true ),
			'user_name'   => self::user_display_name( (int) get_post_meta( $prediction_id, self::META_USER_ID, true ) ),
		);
	}

	public static function finished_unresolved_matches(): array {
		return array_values(
			array_filter(
				array_map(
					static fn ( WP_Post $post ): array => self::match_to_array( (int) $post->ID ),
					get_posts(
						array(
							'post_type'      => Mantia_CPTs::MATCH,
							'post_status'    => 'publish',
							'posts_per_page' => 50,
							'no_found_rows'  => true,
							'meta_query'     => array(
								array(
									'key'   => self::META_STATUS,
									'value' => 'finished',
								),
								array(
									'key'     => self::META_RESOLVED,
									'value'   => '1',
									'compare' => '!=',
								),
							),
						)
					)
				)
			)
		);
	}

	public static function predictions_for_match( int $match_id ): array {
		return array_map(
			static fn ( WP_Post $post ): array => self::prediction_to_array( (int) $post->ID ),
			get_posts(
				array(
					'post_type'      => Mantia_CPTs::PREDICTION,
					'post_status'    => 'publish',
					'posts_per_page' => -1,
					'no_found_rows'  => true,
					'meta_key'       => self::META_MATCH_ID,
					'meta_value'     => $match_id,
				)
			)
		);
	}

	public static function score_prediction_post( int $prediction_id, int $real_home, int $real_away ): array {
		$prediction = self::prediction_to_array( $prediction_id );
		if ( empty( $prediction ) ) {
			return array();
		}

		$score = Mantia_Scoring::score_prediction(
			(int) $prediction['home_score'],
			(int) $prediction['away_score'],
			$real_home,
			$real_away
		);

		update_post_meta( $prediction_id, self::META_POINTS, (int) $score['points'] );
		update_post_meta( $prediction_id, self::META_SCORING_REASON, (string) $score['reason'] );
		update_post_meta( $prediction_id, self::META_SCORED, 1 );

		return array_merge( self::prediction_to_array( $prediction_id ), $score );
	}

	public static function mark_match_resolved( int $match_id ): void {
		update_post_meta( $match_id, self::META_RESOLVED, 1 );
	}

	public static function update_match_result( int $match_id, int $home_score, int $away_score, string $status = 'finished' ): void {
		update_post_meta( $match_id, self::META_HOME_SCORE, max( 0, $home_score ) );
		update_post_meta( $match_id, self::META_AWAY_SCORE, max( 0, $away_score ) );
		update_post_meta( $match_id, self::META_STATUS, sanitize_key( $status ) );
	}

	public static function leaderboard( int $group_id = 0 ): array {
		$args = array(
			'post_type'      => Mantia_CPTs::PREDICTION,
			'post_status'    => 'publish',
			'posts_per_page' => -1,
			'no_found_rows'  => true,
			'meta_query'     => array(
				array(
					'key'   => self::META_SCORED,
					'value' => 1,
				),
			),
		);

		if ( $group_id > 0 ) {
			$args['meta_query'][] = array(
				'key'   => self::META_GROUP_ID,
				'value' => $group_id,
			);
		}

		$rows = array();
		foreach ( get_posts( $args ) as $post ) {
			$prediction = self::prediction_to_array( (int) $post->ID );
			$user_id    = (int) $prediction['user_id'];
			if ( ! isset( $rows[ $user_id ] ) ) {
				$rows[ $user_id ] = array(
					'user_id'     => $user_id,
					'name'        => self::user_display_name( $user_id ),
					'points'      => 0,
					'predictions' => 0,
					'exacts'      => 0,
				);
			}
			$rows[ $user_id ]['points'] += (int) $prediction['points'];
			++$rows[ $user_id ]['predictions'];
			if ( 'exact' === $prediction['reason'] ) {
				++$rows[ $user_id ]['exacts'];
			}
		}

		$rows = array_values( $rows );
		usort(
			$rows,
			static fn ( array $a, array $b ): int => ( $b['points'] <=> $a['points'] )
				?: ( $b['exacts'] <=> $a['exacts'] )
				?: strcasecmp( $a['name'], $b['name'] )
		);

		foreach ( $rows as $index => &$row ) {
			$row['rank'] = $index + 1;
		}

		return $rows;
	}

	public static function user_history( int $user_id, int $group_id = 0 ): array {
		$args = array(
			'post_type'      => Mantia_CPTs::PREDICTION,
			'post_status'    => 'publish',
			'posts_per_page' => 50,
			'no_found_rows'  => true,
			'orderby'        => 'date',
			'order'          => 'DESC',
			'meta_query'     => array(
				array(
					'key'   => self::META_USER_ID,
					'value' => $user_id,
				),
			),
		);

		if ( $group_id > 0 ) {
			$args['meta_query'][] = array(
				'key'   => self::META_GROUP_ID,
				'value' => $group_id,
			);
		}

		return array_map(
			static function ( WP_Post $post ): array {
				$prediction          = self::prediction_to_array( (int) $post->ID );
				$prediction['match'] = self::match_to_array( (int) $prediction['match_id'] );
				return $prediction;
			},
			get_posts( $args )
		);
	}

	public static function users_missing_prediction_for_match( int $match_id, int $group_id = 0 ): array {
		// Query only WhatsApp-managed users — skip site admins / editors etc.
		// They wouldn't have a phone in their meta anyway, but role-filtering
		// is much cheaper than meta-existence.
		$users = get_users( array(
			'role'   => WA_Identity_Bridge::role_slug(),
			'number' => -1,
			'fields' => 'all',
		) );

		$out = array();
		foreach ( $users as $user ) {
			$user_id = (int) $user->ID;
			$groups  = self::user_group_ids( $user_id );
			if ( empty( $groups ) ) {
				continue;
			}
			if ( $group_id > 0 && ! in_array( $group_id, $groups, true ) ) {
				continue;
			}
			$active_group = $group_id > 0 ? $group_id : self::active_group_id_for_user( $user_id );
			if ( $active_group <= 0 ) {
				continue;
			}
			if ( self::find_prediction( $user_id, $match_id, $active_group ) ) {
				continue;
			}
			$out[] = array(
				'user_id'   => $user_id,
				'name'      => self::user_display_name( $user_id ),
				'phone'     => (string) get_user_meta( $user_id, self::META_PHONE, true ),
				'recipient' => (string) get_user_meta( $user_id, self::META_WHATSAPP_RECIPIENT, true ),
				'group_id'  => $active_group,
			);
		}

		return $out;
	}

	private static function nullable_int_meta( int $post_id, string $key ): ?int {
		$value = get_post_meta( $post_id, $key, true );
		return '' === $value ? null : (int) $value;
	}

	private static function match_title( string $home_team, string $away_team ): string {
		return sanitize_text_field( trim( "{$home_team} vs {$away_team}" ) );
	}

	private static function parse_gmt_timestamp( string $value ): int {
		$timestamp = strtotime( $value . ( str_ends_with( $value, 'Z' ) ? '' : ' UTC' ) );
		return false === $timestamp ? time() : $timestamp;
	}

	private static function team_key( string $team ): string {
		$team = function_exists( 'remove_accents' ) ? remove_accents( $team ) : $team;
		return sanitize_title( $team );
	}

	/**
	 * Resolve a fuzzy team name to its canonical fixture form, or '' when
	 * we don't recognise it. Used by the bulk-back-team flow so users can
	 * type "argentina" / "Argentina!" / "ARG" and we still anchor it to
	 * the exact label the match CPT stores ("Argentina"), which the
	 * register_prediction matcher then compares for orientation.
	 *
	 * Cached for the request so a "Argentina gana todo" command doesn't
	 * re-scan all 64 matches once per fixture row.
	 */
	public static function team_canonical( string $raw ): string {
		static $cache = null;
		if ( null === $cache ) {
			$cache = array();
			$posts = get_posts(
				array(
					'post_type'      => Mantia_CPTs::MATCH,
					'posts_per_page' => -1,
					'post_status'    => 'publish',
					'fields'         => 'ids',
				)
			);
			foreach ( $posts as $pid ) {
				foreach ( array( self::META_HOME_TEAM, self::META_AWAY_TEAM ) as $meta_key ) {
					$name = (string) get_post_meta( (int) $pid, $meta_key, true );
					if ( '' === $name ) {
						continue;
					}
					$cache[ self::team_key( $name ) ] = $name;
				}
			}
		}

		$key = self::team_key( trim( $raw ) );
		return $cache[ $key ] ?? '';
	}

	/* ------------------------------ Sweepstake ----------------------------- */

	/**
	 * All unique team names appearing in a competition's match fixture.
	 * Order is unspecified — sweepstake shuffles before assigning anyway.
	 *
	 * @return array<int,string>
	 */
	public static function teams_in_competition( string $competition_id ): array {
		$storage_id = Mantia_Competitions::storage_id( $competition_id );
		if ( '' === $storage_id ) {
			return array();
		}
		$ids = get_posts( array(
			'post_type'      => Mantia_CPTs::MATCH,
			'post_status'    => 'publish',
			'posts_per_page' => -1,
			'fields'         => 'ids',
			'no_found_rows'  => true,
			'meta_query'     => array(
				array( 'key' => Mantia_Competitions::META_KEY, 'value' => $storage_id ),
			),
		) );
		$teams = array();
		foreach ( (array) $ids as $mid ) {
			foreach ( array( self::META_HOME_TEAM, self::META_AWAY_TEAM ) as $meta_key ) {
				$name = (string) get_post_meta( (int) $mid, $meta_key, true );
				if ( '' !== $name && ! in_array( $name, $teams, true ) ) {
					$teams[] = $name;
				}
			}
		}
		return $teams;
	}

	private static function sweepstake_meta_key( int $group_id ): string {
		return self::META_SWEEPSTAKE_TEAM . max( 0, $group_id );
	}

	public static function get_sweepstake_team( int $user_id, int $group_id ): string {
		if ( $user_id <= 0 || $group_id <= 0 ) {
			return '';
		}
		return (string) get_user_meta( $user_id, self::sweepstake_meta_key( $group_id ), true );
	}

	public static function set_sweepstake_team( int $user_id, int $group_id, string $team ): void {
		if ( $user_id <= 0 || $group_id <= 0 ) {
			return;
		}
		if ( '' === $team ) {
			delete_user_meta( $user_id, self::sweepstake_meta_key( $group_id ) );
			return;
		}
		update_user_meta( $user_id, self::sweepstake_meta_key( $group_id ), sanitize_text_field( $team ) );
	}

	/**
	 * Draw a sweepstake for the group: every current member gets one
	 * random team from the group's competition fixture. Returns the
	 * resulting map { user_id => team_name }. If there are more members
	 * than unique teams the extras get '' (callers should surface that
	 * as "no te tocó ninguno" instead of pretending success).
	 *
	 * @return array<int,string>
	 */
	public static function assign_sweepstake( int $group_id ): array {
		$members = self::group_members( $group_id );
		if ( empty( $members ) ) {
			return array();
		}
		$competition_id = self::group_competition_id( $group_id );
		$teams = self::teams_in_competition( $competition_id );
		if ( empty( $teams ) ) {
			return array();
		}

		shuffle( $teams );
		$assignments = array();
		foreach ( array_values( $members ) as $i => $m ) {
			$user_id = (int) ( $m['id'] ?? 0 );
			if ( $user_id <= 0 ) {
				continue;
			}
			$team = isset( $teams[ $i ] ) ? (string) $teams[ $i ] : '';
			self::set_sweepstake_team( $user_id, $group_id, $team );
			$assignments[ $user_id ] = $team;
		}
		return $assignments;
	}

	/**
	 * Read out the current sweepstake map for a group, in member-order.
	 * Used for the "mi sorteo" reply and for the matchday workflow that
	 * pushes "your team plays today" reminders.
	 *
	 * @return array<int,array{user_id:int,name:string,team:string}>
	 */
	public static function sweepstake_for_group( int $group_id ): array {
		$rows = array();
		foreach ( self::group_members( $group_id ) as $m ) {
			$user_id = (int) ( $m['id'] ?? 0 );
			if ( $user_id <= 0 ) {
				continue;
			}
			$rows[] = array(
				'user_id' => $user_id,
				'name'    => (string) ( $m['display_name'] ?? '' ),
				'team'    => self::get_sweepstake_team( $user_id, $group_id ),
			);
		}
		return $rows;
	}
}
